### ISSUE TITLE
Package(s) used for tables

### ISSUE THREAD

**Issue by 11rchitwood** [jdbarillas/executive_summary#2]
I am running into several issues styling tables in pagedown using the new [gt package](https://github.com/rstudio/gt). @jdbarillas, what package(s) are you using for tables?

Also, have you figured out how to deal with multipage tables as in rstudio/pagedown#162?

**Comment by jdbarillas** [comment]
We used the `gt` package as well for the styling of tables. In term of dealing with multipage tables, we used the code in the issue you linked to make sure the tables had repeated headers when we knit the document. 

If you have any questions, let me know.

**Comment by 11rchitwood** [comment]
Perfect. We are using `gt` as well. Hoping to open source our theme when we are done. Thanks!

**Comment by jdbarillas** [comment]
I posted some of the custom CSS and code for a webinar I conducted here https://github.com/jdbarillas/trug_pagedown No `gt` used though.

**Comment by 11rchitwood** [comment]
Great. Thanks @jdbarillas!
